/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab5;
import javax.swing.JOptionPane;
/**
 *
 * @author KALAHI CIDSS
 */
public class Frame extends javax.swing.JFrame {
    SinglyLinkedList list = new SinglyLinkedList();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frame.class.getName());

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        Input = new javax.swing.JTextField();
        topInsert = new javax.swing.JButton();
        botInsert = new javax.swing.JButton();
        delId = new javax.swing.JButton();
        delName = new javax.swing.JButton();
        delInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Display.setEditable(false);
        Display.setBackground(new java.awt.Color(204, 204, 204));
        Display.setColumns(20);
        Display.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Display.setForeground(new java.awt.Color(0, 0, 0));
        Display.setRows(5);
        Display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane1.setViewportView(Display);

        Input.setBackground(new java.awt.Color(255, 255, 255));
        Input.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Input.setForeground(new java.awt.Color(0, 0, 0));
        Input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input.setText("Input Names");
        Input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        topInsert.setBackground(new java.awt.Color(0, 0, 255));
        topInsert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        topInsert.setForeground(new java.awt.Color(0, 0, 0));
        topInsert.setText("Insert(Top)");
        topInsert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        topInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topInsertActionPerformed(evt);
            }
        });

        botInsert.setBackground(new java.awt.Color(0, 0, 255));
        botInsert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botInsert.setForeground(new java.awt.Color(0, 0, 0));
        botInsert.setText("Insert(Bottom)");
        botInsert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInsertActionPerformed(evt);
            }
        });

        delId.setBackground(new java.awt.Color(204, 0, 0));
        delId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        delId.setForeground(new java.awt.Color(0, 0, 0));
        delId.setText("Delete(via Id)");
        delId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        delId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delIdActionPerformed(evt);
            }
        });

        delName.setBackground(new java.awt.Color(204, 0, 0));
        delName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        delName.setForeground(new java.awt.Color(0, 0, 0));
        delName.setText("Delete(via Names)");
        delName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        delName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delNameActionPerformed(evt);
            }
        });

        delInput.setBackground(new java.awt.Color(255, 255, 255));
        delInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        delInput.setForeground(new java.awt.Color(0, 0, 0));
        delInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        delInput.setText("Delete Names");
        delInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        delInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(topInsert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Input, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delInput)
                            .addComponent(delName, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Input)
                    .addComponent(delInput, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(delName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputActionPerformed

    private void delInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delInputActionPerformed

    private void topInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topInsertActionPerformed
        String input = Input.getText();
        if (input.equalsIgnoreCase("Input Names")){
            Input.setText("");
            return;
        }
        if (input.isBlank()){
            return;
        }
        list.insertStart(input);
        Input.setText("");
        display();
    }//GEN-LAST:event_topInsertActionPerformed

    private void botInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInsertActionPerformed
        String input = Input.getText();
        if (input.equalsIgnoreCase("Input Names")){
            Input.setText("");
            return;
        }
        if (input.isBlank()){
            return;
        }
        list.insertEnd(input);
        Input.setText("");
        display();
    }//GEN-LAST:event_botInsertActionPerformed

    private void delIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delIdActionPerformed
        String text = delInput.getText();
        if (text.equalsIgnoreCase("Delete Names")){
            delInput.setText("");
            return;
        }
        
        int input = 0;
        try {
            input = Integer.parseInt(text);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter numeric id (n. >>id<< Name)", "Input Error", JOptionPane.ERROR_MESSAGE);
            delInput.setText("");
            return;
        }
        String result = list.deleteId(input);
        if (result =="0"){
            JOptionPane.showMessageDialog(this, "Did not find data matching input", "Match Error", JOptionPane.ERROR_MESSAGE);
            delInput.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Successfully deleted " + result);
        }
        display();
        delInput.setText("");
    }//GEN-LAST:event_delIdActionPerformed

    private void delNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delNameActionPerformed
        String input = delInput.getText();
        if (input.equalsIgnoreCase("Delete Names")){
            delInput.setText("");
            return;
        }
        String result = list.deleteName(input);
        if (result=="0"){
            JOptionPane.showMessageDialog(this, "Did not find data matching input", "Match Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Successfully deleted " + result);
        }
        display();
        delInput.setText("");
    }//GEN-LAST:event_delNameActionPerformed

    public void display(){
        String display = list.display();
        Display.setText(display);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Display;
    private javax.swing.JTextField Input;
    private javax.swing.JButton botInsert;
    private javax.swing.JButton delId;
    private javax.swing.JTextField delInput;
    private javax.swing.JButton delName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton topInsert;
    // End of variables declaration//GEN-END:variables
}
